### ISSUE TITLE
Support for English language in menus of the "plugin.audio.radio_de_light" ?

### ISSUE THREAD

**Issue by jcjdammers** [Publish3r/repository.kodi.matrix#8]
Hi,
Currently the menus of the plugin.audio.radio_de_light are in German language.
Would it be possible to add the English language as well?
Thanks.

**Comment by Publish3r** [comment]
Hi. If i have time in the next days i can do it.
But i recommend to use this addon. It supports the new api, too. And it has more features.
https://github.com/fivebanger/kodi_addons/tree/master/plugin.audio.radiode
